@startuml
'https://plantuml.com/use-case-diagram

usecase 5.24

usecase 5.25
usecase 5.26
usecase 5.27
usecase 5.28
usecase 5.29
'usecase 5.30
'usecase 5.31
'usecase 6.1
'usecase 6.2
usecase 6.3
usecase 6.4
usecase 6.5
'usecase 6.6
'usecase 6.7
'usecase 6.8
'usecase 6.9
'usecase 6.10
usecase 6.11
usecase 6.12
'usecase 6.13
usecase 6.14
usecase 6.15

5.24->5.25
5.25->5.26
5.26->5.27
5.27->5.28
5.28->5.29
'5.29->5.30
5.29->6.3:5.30到6.2号\n休带薪假\n(4天)
'5.31->6.1
'6.1->6.2
'6.2->6.3
6.3->6.4
6.4->6.5
6.5->6.11:6.6到6.10号\n休带薪假\n(5天)
'6.7->6.8
'6.8->6.9
'6.9->6.10
'6.10->6.11
6.11->6.12
6.12->6.14:6.13到6.14号\n休带薪假\n(1.5天)
'6.13->6.14
6.14->6.15


note top of 5.24:公司发送单\n方解除通知\n书,被关闭\n全部权限(单\n方解除通知\n书证据)
note top of 5.25:公司未经协\n商,单方面\n定最后工作\n日
note bottom of 5.25:hr打电话\n过来和我协\n商,(关权限\n后,只有hr\n文静的电话\n联系方式)\n,要求请假修\n完剩余10.5\n天年假,hr\n和主管同意了\n休假(电话录\n音证据)
note bottom of 5.26:居家办公\n(截图证据)
note bottom of 5.27:居家办公\n(截图证据)
note top of 5.28:周六
note top of 5.29:周日
note bottom of 5.29:收到单方解\n除通知书,\n没有通知金,\n也没有提前\n30天通知,\n违反劳动合\n同法第40条\n(快递单截图\n证据)
'note bottom of 5.30:5.25已经和\nhr主管请假\n并同意,处于\n休假中
note bottom of 6.4:工作满2年\n,200股阿里\n股票归属\n(劳动合同证\n据,归属协证\n据)
note bottom of 6.14:10.5天年假休完
note top of 6.3:端午节
note top of 6.4:周六
note top of 6.5:周日
note top of 6.11:周六
note top of 6.12:周日
note top of 6.15:实际最后工作日
note bottom of 6.15:返岗工作,门\n禁卡进不去,\n无法进去工\n作,要求拿回\n私人物品,被\n拒(返岗视\n频证据)




@enduml